let data = [
    {   "primary-key": "00001",
        "product": "Vintersko",
        "brand":"Nike",
        "cat" : ["men", "women","children"],
        // "sizes": ["xxs","xs","s","l","xl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","45-46"],
        "colors" : ["rød", "gul", "grå"],
        "price": 400.00,
        "image": "images/nike/n-winter1.jpg"
    },
    {   "primary-key": "00002",
        "product": "Vintersko",
        "brand":"Nike",
        "cat" : ["men", "women","children"],
        // "sizes": ["xs","s","m","xxl"],
        "sizes": ["18-22","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 650.00,
        "image": "images/nike/n-winter2.jpg"
    }, 
    {
        "primary-key": "00003",
        "product": "Sommersko",
        "brand":"Nike",
        "cat" : ["men", "women"],
        // "sizes": ["m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","38-40","42-44"],
        "colors" : ["rød", "blå","sort", "grå"],
        "price": 2000.00,
        "image": "images/nike/n-summer1.jpg"
    },
    {
        "primary-key": "00004",
        "product": "Sommersko",
        "brand":"Nike",
        "cat" : ["men", "women"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul", "grå"],
        "price": 2500.00,
        "image": "images/nike/n-summer2.jpg"
    },
    {
        "primary-key": "00005",
        "product": "Regnsko",
        "brand":"Nike",
        "cat" : ["men", "women","children"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["24-28","30-36","38-40","42-44"],
        "colors" : ["blå", "gul","sort", "grå"],
        "price": 400.00,
        "image": "images/nike/n-rain1.jpg"
    },
    {
        "primary-key": "00006",
        "product": "Regnsko",
        "brand":"Nike",
        "cat" : ["women"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 400.00,
        "image": "images/nike/n-rain2.jpg"
    },
    {
        "primary-key": "00007",
        "product": "Sportssko",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","42-44"],
        "colors" : ["rød", "blå", "gul","sort"],
        "price": 1200.00,
        "image": "images/nike/n-sports1.jpg"
    },
    {
        "primary-key": "00008",
        "product": "Sportssko",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 1200.00,
        "image": "images/nike/n-sports2.jpg"
    },
    {
        "primary-key": "00009",
        "product": "Sandel",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 950.00,
        "image": "images/nike/n-sandal1.jpg"
    },
    {
        "primary-key": "00010",
        "product": "Sandel",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "gul","sort", "grå"],
        "price": 950.00,
        "image": "images/nike/n-sandal2.jpg"
    },
    {
        "primary-key": "00011",
        "product": "Løbesko",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["16-18","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 950.00,
        "image": "images/nike/n-running1.jpg"
    },
    {
        "primary-key": "00012",
        "product": "Løbesko",
        "brand":"Nike",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "lilla","sort", "grå"],
        "price": 950.00,
        "image": "images/nike/n-running2.jpg"
    },
    
    {   "primary-key": "00013",
        "product": "Vintersko",
        "brand":"Adidas",
        "cat" : ["men", "women","children"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 400.00,
        "image": "images/adidas/a-winter1.jpg"
    },
    {   "primary-key": "00014",
        "product": "Vintersko",
        "brand":"Adidas",
        "cat" : ["men", "women","children"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå","sort", "grå"],
        "price": 650.00,
        "image": "images/adidas/a-winter2.jpg"
    }, 
    {
        "primary-key": "00015",
        "product": "Sommersko",
        "brand":"Adidas",
        "cat" : ["men", "women","children"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "sort","lilla"],
        "price": 2000.00,
        "image": "images/adidas/a-summer1.jpg"
    },
    {
        "primary-key": "00016",
        "product": "Sommersko",
        "brand":"Adidas",
        "cat" : ["men", "women"],
        // "sizes": ["m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "gul","sort", "grå"],
        "price": 2500.00,
        "image": "images/adidas/a-summer2.jpg"
    },
    {
        "primary-key": "00017",
        "product": "Regnsko",
        "brand":"Adidas",
        "cat" : ["women"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "grå"],
        "price": 400.00,
        "image": "images/adidas/a-rain1.jpg"
    },
    {
        "primary-key": "00018",
        "product": "Regnsko",
        "brand":"Adidas",
        "cat" : ["women"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "brun","sort", "grå"],
        "price": 400.00,
        "image": "images/adidas/a-rain2.jpg"
    },
    {
        "primary-key": "00019",
        "product": "Sportssko",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "grå"],
        "price": 1200.00,
        "image": "images/adidas/a-sports1.jpg"
    },
    {
        "primary-key": "00020",
        "product": "Sportssko",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "sort", "grå"],
        "price": 1200.00,
        "image": "images/adidas/a-sports2.jpg"
    },
    {
        "primary-key": "00021",
        "product": "Sandel",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "grå"],
        "price": 950.00,
        "image": "images/adidas/a-sandal1.jpg"
    },
    {
        "primary-key": "00022",
        "product": "Sandel",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["blå", "brun","sort", "grå"],
        "price": 950.00,
        "image": "images/adidas/a-sandal2.jpg"
    },
    {
        "primary-key": "00023",
        "product": "Arbejdssko",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "hvid","sort", "grå"],
        "price": 1000.00,
        "image": "images/adidas/a-working1.jpg"
    },
    {
        "primary-key": "00024",
        "product": "Arbejdssko",
        "brand":"Adidas",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 1000.00,
        "image": "images/adidas/a-working1.jpg"
    },
    
    
    {   "primary-key": "00025",
        "product": "Vintersko",
        "brand":"Hummel",
        "cat" : ["men", "women","children"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "brun","sort", "hvid"],
        "price": 400.00,
        "image": "images/hummel/h-winter1.png"
    },
    {   "primary-key": "00026",
        "product": "Vintersko",
        "brand":"Hummel",
        "cat" : ["men", "women","children"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 650.00,
        "image": "images/hummel/h-winter2.png"
    }, 
    {
        "primary-key": "00027",
        "product": "Sommersko",
        "brand":"Hummel",
        "cat" : ["men", "women"],
        // "sizes": ["xxs","xs","s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun"],
        "price": 2000.00,
        "image": "images/hummel/h-summer1.png"
    },
    {
        "primary-key": "00028",
        "product": "Sommersko",
        "brand":"Hummel",
        "cat" : ["men", "women"],
        // "sizes": ["m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 2500.00,
        "image": "images/hummel/h-summer2.png"
    },
    
    {
        "primary-key": "00029",
        "product": "Sportssko",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["brun","sort", "hvid"],
        "price": 1200.00,
        "image": "images/hummel/h-sports1.png"
    },
    {
        "primary-key": "00030",
        "product": "Sportssko",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 1200.00,
        "image": "images/hummel/h-sports2.png"
    },
    {
        "primary-key": "00031",
        "product": "Sandel",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød","sort", "hvid"],
        "price": 950.00,
        "image": "images/hummel/h-sandal1.png"
    },
    {
        "primary-key": "00032",
        "product": "Sandel",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 950.00,
        "image": "images/hummel/h-sandal2.png"
    },
    {
        "primary-key": "00033",
        "product": "Arbejdssko",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun"],
        "price": 1000.00,
        "image": "images/hummel/h-working1.png"
    },
    {
        "primary-key": "00034",
        "product": "Arbejdssko",
        "brand":"Hummel",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 1000.00,
        "image": "images/hummel/h-working1.png"
    },
    {   
        "primary-key": "00035",
        "product": "Vintersko",
        "brand":"Puma",
        "cat" : ["men", "women","children"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["blå", "brun","sort", "hvid"],
        "price": 400.00,
        "image": "images/puma/p-winter1.jpg"
    },
    {   "primary-key": "00036",
        "product": "Vintersko",
        "brand":"Puma",
        "cat" : ["men", "women","children"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 650.00,
        "image": "images/puma/p-winter2.jpg"
    }, 
    {
        "primary-key": "00037",
        "product": "Sommersko",
        "brand":"Puma",
        "cat" : ["men", "women"],
        // "sizes": ["m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "brun","sort", "hvid"],
        "price": 2000.00,
        "image": "images/puma/p-summer1.jpg"
    },
    {
        "primary-key": "00038",
        "product": "Sommersko",
        "brand":"Puma",
        "cat" : ["men", "women"],
        // "sizes": ["m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "Pink","sort", "gul"],
        "price": 2500.00,
        "image": "images/puma/p-summer2.jpg"
    },
    {
        "primary-key": "00039",
        "product": "Regnsko",
        "brand":"Puma",
        "cat" : ["women"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "Pink","sort", "gul"],
        "price": 400.00,
        "image": "images/puma/p-rain1.jpg"
    },
    {
        "primary-key": "00040",
        "product": "Regnsko",
        "brand":"Puma",
        "cat" : ["women"],
        // "sizes": ["s","m","l","xl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "Pink", "gul"],
        "price": 400.00,
        "image": "images/puma/p-rain2.jpg"
    },
    {
        "primary-key": "00041",
        "product": "Sportssko",
        "brand":"Puma",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["rød", "blå", "Pink","sort", "grøn"],
        "price": 1200.00,
        "image": "images/puma/p-sports1.jpg"
    },
    {
        "primary-key": "00042",
        "product": "Sportssko",
        "brand":"Puma",
        "cat" : ["men","women","children"],
        // "sizes": ["s","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "grøn", "Pink","sort", "gul"],
        "price": 1200.00,
        "image": "images/puma/p-sports2.jpg"
    },
    {
        "primary-key": "00043",
        "product": "Sandel",
        "brand":"Puma",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["16-18","18-22","24-28","30-36","38-40","42-44","45-46"],
        "colors" : ["blå", "Pink","sort", "gul"],
        "price": 950.00,
        "image": "images/puma/p-sandal1.jpg"
    },
    {
        "primary-key": "00044",
        "product": "Sandel",
        "brand":"Puma",
        "cat" : ["men","women","children"],
        // "sizes": ["xxs","xs","m","l","xl", "xxl"],
        "sizes": ["18-22","24-28","30-36","38-40","42-44"],
        "colors" : ["rød", "blå", "Pink","sort", "gul"],
        "price": 950.00,
        "image": "images/puma/p-sandal2.jpg"
    },
    
]